export const SET_MESSAGE = 'SET_MESSAGE';
export const SET_SELECTED_FILE = 'SET_SELECTED_FILE';
export const SET_NETWORK_ACTION = 'SET_NETWORK_ACTION';
export const SET_CLIP_BOARD_ITEM = 'SET_CLIP_BOARD_ITEM';
export const AUTHENTIICATED = 'AUTHENTIICATED';